---
- hosts: all
  become: true
  tasks:
      - name: installing packages
        apt:
            name: "{{ item }}" 
            state: present
            update_cache: yes
        with_items:
            -git
            -wget
            -tree        
