---
- hosts: group
  become: true
  tasks:
      - name: installing packages in ubuntu
        apt:
            name: git 
            state: present
            update_cache: yes
        when: ansible_os_family == "Debian"
      - name: installing packages in redhat
        yum:
            name: git
            state: present
            update_cache: yes
        when: ansible_os_family == "RedHat"        
